# Configuración del sitio
title: Eitb Noticias
description: "Noticias con contexto."
baseurl: "" # Dejar vacío para GitHub Pages si se publica en el root
url: "https://www.eitbnoticias.com" # URL base del sitio
repository: N3cr0N3ws/eitbnoticias # Reemplaza con tu usuario y repositorio de GitHub

# Configuración del generador de páginas
page_gen:
  - data: 'source'        # Archivo de datos (ubicado en _data/source.json)
    template: 'page'      # Plantilla usada para generar páginas (en _layouts/page.html)
    name: 'titulo'        # Campo que define el nombre de cada página
    dir: 'pages'          # Directorio donde se generarán las páginas

# Archivos y carpetas excluidos del procesamiento
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - _posts/
  - _layouts/post.html
  - vendor
