# Configuración general del sitio
title: Eitb Noticias
description: "Noticias con contexto."
url: "http://localhost:4000" # URL para desarrollo local o producción
baseurl: "" # Vacío porque el sitio está en el root del dominio

# Directorios y exclusiones
exclude:
  - _plugins # No se procesarán estos directorios
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - _posts # No usarás posts

# Configuración de Jekyll
markdown: kramdown
data_dir: "_data"

# JSON fuente para producción
json_source: "source.json"
