# Configuración general del sitio
title: Eitb Noticias
description: "Noticias con contexto."
url: "https://www.eitbnoticias.com" # URL para desarrollo local o producción
baseurl: "" # Vacío porque el sitio está en el root del dominio

# Directorios y exclusiones
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _posts
  - mergeJson.js

# Configuración de Jekyll
markdown: kramdown
data_dir: "_data"
