# Configuración general del sitio
title: Eitb Noticias (Local)
description: "Noticias con contexto. Desarrollo Local"
url: "http://localhost:4000" # URL local del sitio
baseurl: "" # Vacío para desarrollo

# Directorios y plugins personalizados
plugins_dir: "_plugins" # Directorio donde están los plugins
data_dir: "_data" # Directorio de datos

# Configuración de Jekyll
markdown: kramdown

# Directorios y exclusiones
exclude:
  - vendor
  - assets/css
  - index.html

# Configuración de Liquid para manejo estricto de variables
liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true