source "https://rubygems.org"

# Usar la versión de Jekyll y plugins compatibles con GitHub Pages
gem "github-pages", group: :jekyll_plugins

# Windows y JRuby: soporte adicional
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Booster de rendimiento para Windows
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]
