name: Backup source.json

on:
  push:
    branches:
      - merge-temp-4

jobs:
  backup-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create _backup directory if it doesn't exist
        run: |
          mkdir -p _backup

      - name: Backup source.json
        run: |
          cp _data/source.json _backup/source-$(date +'%Y%m%d%H%M%S').json

      - name: List contents of _backup directory
        run: |
          ls -la _backup
