name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - merge-temp-4

jobs:
  merge-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Update and merge JSON files
        run: node _data/mergeJson.js

      - name: Inspect merged JSON
        run: cat _data/source.json

      - name: Commit and push merged JSON
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./_data
          publish_branch: merge-temp-4
          keep_files: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true

      - name: Clean _site directory
        run: |
          rm -rf _site || true
          mkdir _site

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Verify _site directory
        run: |
          echo "Contents of _site directory:"
          ls -la ${{ github.workspace }}/_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ${{ github.workspace }}/_site
          publish_branch: gh-pages
          keep_files: true
          force_orphan: false
