name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Ruby para Jekyll
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: bundle install

      # Paso 4: Construir el sitio estático con Jekyll
      - name: Build Jekyll site
        run: JEKYLL_ENV=production bundle exec jekyll build

      # Paso 5: Verificar archivos generados
      - name: List generated files
        run: ls -R _site

      # Paso 6: Desplegar el sitio en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
