name: Actualizar source.json con og:image

on:
  push:
    branches:
      - merge-temp-4

jobs:
  update-source-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Run mergeJson.js script
        run: node mergeJson.js

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Add and commit changes
        run: |
          git add _data/source.json _data/update.json
          git commit -m "Actualizar source.json con og:image"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin HEAD:${{ github.ref }}
